/* eslint-disable prettier/prettier */
export type limpiezaMensualType = {
  fecha:string
    //Area cuartos
  area_cuartos_cortinas?: string
  area_cuartos_muelle?: string
  area_cuartos_pisos?: string
  area_cuartos_ventiladores?: string
  //Area recepcion
  area_recepcion_pisos?: string;
  area_recepcion_estibas?: string;
  area_recepcion_anjeos?: string;
  area_recepcion_vigas?: string;
  area_recepcion_muelles?: string;
  area_recepcion_desverdizado?: string;
  area_recepcion_tanque?: string;
  area_recepcion_soporte?: string;
  area_recepcion_oficina?: string;
  area_recepcion_estibadores?: string;
  area_recepcion_tanqueInmersion?: string;
  area_recepcion_banda?: string;
  area_recepcion_filtro?: string;
  area_recepcion_canecas?: string;
  area_recepcion_cortinas?: string;
  //Area Lavado 
  area_lavado_paredes?: string;
  area_lavado_anjeos?: string;
  area_lavado_extractores?: string;
  area_lavado_rodillos?: string;
  area_lavado_rodillosLavado?: string;
  area_lavado_extractoresSecado?: string;
  //Area produccion
  area_produccion_pisos?: string;
  area_produccion_ventiladores?: string;
  area_produccion_paredes?: string;
  area_produccion_ventiladoresPiso?: string;
  area_produccion_rodillosEncerados?: string;
  area_produccion_cilindro?: string;
  area_produccion_clasificadora?: string;
  area_produccion_bandejas?: string;
  area_produccion_soportes?: string;
  area_produccion_extractores?: string;
  area_produccion_anjeos?: string;
  area_produccion_cuarto?: string;
  area_produccion_oficina?: string;
  area_produccion_laboratorio?: string;
  area_produccion_filtro?: string;
  area_produccion_canecas?: string;
  area_produccion_estibadores?: string;
  area_produccion_escaleras?: string;
  area_produccion_carritos?: string;
  area_produccion_herramientas?: string;
  //area pasillo
  area_pasillo_pisos?: string;
  //Area carton
  area_carton_pisos?: string;
  area_carton_esstibadores?: string;
  //Area sociales
  area_sociales_lockers?: string;
  area_sociales_comedor?: string;
  area_sociales_nevera?: string;
  area_sociales_hornos?: string;
  area_sociales_pisos?: string;
  area_sociales_paredes?: string;
  area_sociales_anjeos?: string;
  area_sociales_canecas?: string;
  area_sociales_exteriores?: string;
  area_sociales_comedorExterior?: string;
  //Obs cuartos
  area_cuartos_cortinas_observaciones?: string;
  area_cuartos_muelle_observaciones?: string;
  area_cuartos_pisos_observaciones?: string;
  area_cuartos_ventiladores_observaciones?: string;
  //Obs recepcion
  area_recepcion_pisos_observaciones?: string;
  area_recepcion_estibas_observaciones?: string;
  area_recepcion_anjeos_observaciones?: string;
  area_recepcion_vigas_observaciones?: string;
  area_recepcion_muelles_observaciones?: string;
  area_recepcion_desverdizado_observaciones?: string;
  area_recepcion_tanque_observaciones?: string;
  area_recepcion_soporte_observaciones?: string;
  area_recepcion_oficina_observaciones?: string;
  area_recepcion_estibadores_observaciones?: string;
  area_recepcion_tanqueInmersion_observaciones?: string;
  area_recepcion_banda_observaciones?: string;
  area_recepcion_filtro_observaciones?: string;
  area_recepcion_canecas_observaciones?: string;
  area_recepcion_cortinas_observaciones?: string;
  // Obs Lavavdo
  area_lavado_paredes_observaciones?: string;
  area_lavado_anjeos_observaciones?: string;
  area_lavado_extractores_observaciones?: string;
  area_lavado_rodillos_observaciones?: string;
  area_lavado_rodillosLavado_observaciones?: string;
  area_lavado_extractoresSecado_observaciones?: string;
  //Obs produccion
  area_produccion_pisos_observaciones?: string;
  area_produccion_ventiladores_observaciones?: string;
  area_produccion_paredes_observaciones?: string;
  area_produccion_ventiladoresPiso_observaciones?: string;
  area_produccion_rodillosEncerados_observaciones?: string;
  area_produccion_cilindro_observaciones?: string;
  area_produccion_clasificadora_observaciones?: string;
  area_produccion_bandejas_observaciones?: string;
  area_produccion_soportes_observaciones?: string;
  area_produccion_extractores_observaciones?: string;
  area_produccion_anjeos_observaciones?: string;
  area_produccion_cuarto_observaciones?: string;
  area_produccion_oficina_observaciones?: string;
  area_produccion_laboratorio_observaciones?: string;
  area_produccion_filtro_observaciones?: string;
  area_produccion_canecas_observaciones?: string;
  area_produccion_estibadores_observaciones?: string;
  area_produccion_escaleras_observaciones?: string;
  area_produccion_carritos_observaciones?: string;
  area_produccion_herramientas_observaciones?: string;
  //Obs pasillo
  area_pasillo_pisos_observaciones?: string;
  //obs carton
  area_carton_pisos_observaciones?: string;
  area_carton_estibadores_observaciones?: string;
  //obs sociales
  area_sociales_lockers_observaciones?: string;
  area_sociales_comedor_observaciones?: string;
  area_sociales_nevera_observaciones?: string;
  area_sociales_hornos_observaciones?: string;
  area_sociales_pisos_observaciones?: string;
  area_sociales_paredes_observaciones?: string;
  area_sociales_anjeos_observaciones?: string;
  area_sociales_canecas_observaciones?: string;
  area_sociales_exteriores_observaciones?: string;
  area_sociales_comedorExterior_observaciones?: string;
}
